FROM alpine:latest

RUN apk --no-cache add unbound openssl wget dnssec-root

#Debugging
RUN apk --no-cache add iproute2 bind-tools tcpdump

RUN printf '%s\n' \
    "include: /etc/unbound/conf.d/*.conf" \
    "include: /etc/unbound/local.d/*.conf" \
    | tee -a /etc/unbound/unbound.conf \
    && sed -i '/root-hints:/d' /etc/unbound/unbound.conf

COPY config/unbound/conf.d/  /etc/unbound/conf.d/
COPY config/unbound/local.d/ /etc/unbound/local.d/
COPY entrypoints/unbound.sh  /entrypoint.sh

RUN /etc/periodic/monthly/update-unbound-root-hints

EXPOSE 53/udp 53/tcp

ENTRYPOINT [ "/entrypoint.sh" ]

CMD [ "/usr/sbin/unbound", "-dvv" ]
