FROM alpine:3.10

RUN apk --no-cache add unbound openssl wget curl dnssec-root

#Debugging
#RUN apk --no-cache add iproute2 bind-tools tcpdump

RUN printf '%s\n' \
    "include: /etc/unbound/conf.d/*.conf" \
    "include: /etc/unbound/local.d/*.conf" \
    | tee -a /etc/unbound/unbound.conf \
    && curl --output /usr/share/dns-root-hints/named.root https://www.internic.net/domain/named.cache \
    && unbound-anchor -Fv || true


COPY config/unbound/conf.d/  /etc/unbound/conf.d/
COPY config/unbound/local.d/ /etc/unbound/local.d/
COPY entrypoints/unbound.sh  /entrypoint.sh

EXPOSE 53/udp 53/tcp

ENTRYPOINT [ "/entrypoint.sh" ]

CMD [ "/usr/sbin/unbound", "-d" ]
